### ISSUE TITLE
nepřesné matematické výpočty v návrhu testu

### ISSUE THREAD

**Issue by pavelDohnalik** [RDDG/DuckCalcVyvoj#1]
Nepřesné matematické výpočty v návrhu testů, typu 1 + 1 očekávaná hodnota 1 (má být 2 apod) 
@dolefi  prosím o opravu a správné matematické výsledky

**Comment by Fijasko** [comment]
např. řádek 38, 39, ...

**Comment by pavelDohnalik** [comment]
@dolefi prosím o opravu opravených testů :D např řádek 35, 66...

**Comment by pavelDohnalik** [comment]
97
