### ISSUE TITLE
Testy - čísla s nekonečným desetinným rozvojem

### ISSUE THREAD

**Issue by Fijasko** [RDDG/DuckCalcVyvoj#2]
Nemyslím si, že je vhodné používat pro testy příklady, jejichž výsledky vychází s nekonečným desetinným rozvojem (řádky 67 a 112), protože není jasné, kolik desetinných míst budou vracet metody z matematické knihovny.

**Comment by dolefi** [comment]
v souboru s návrhem testů je napsáno co se má v takovém případě stát. Testovat se takové vstupy musí.
